version: '3.8'

services:
  microservice1:
    build:
      context: ./Microservice1
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db
      - microservice2
    restart: on-failure
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=${DB_NAME};Username=${DB_USERNAME};Password=${DB_PASSWORD};
    networks:
      - app_network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app_network
  
  microservice2:
    build:
      context: ./microservice2
      dockerfile: Dockerfile
    ports:
      - "8081:8000"
    depends_on:
      - db
    restart: on-failure
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
        - app_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
